server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaex0pwexo15qIHu0h7
            client-secret: remoCDeK42gqFZxBDCfrNmopcIc_Kjfu-dklqCsD
        provider:
          okta:
            authorization-uri: https://dev-860434.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-860434.oktapreview.com/oauth2/v1/token
            user-info-uri: https://dev-860434.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-860434.oktapreview.com/oauth2/v1/keys