server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: your-okta-client-id
            client-secret: your-okta-client-secret
        provider:
          okta:
            authorization-uri: https://<your-okta-subdomain>.oktapreview.com/oauth2/v1/authorize
            token-uri: https://<your-okta-subdomain>.oktapreview.com/oauth2/v1/token
            user-info-uri: https://<your-okta-subdomain>.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://<your-okta-subdomain>.oktapreview.com/oauth2/v1/keys